version: "3.7"
services:
  app:
    container_name: peakspace-api
    image: peakspace-api
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ..:/app:cached
      # - vendor:/app/vendor
      # - node_modules:/app/node_modules
      - ./server-config/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./server-config/nginx.conf:/etc/nginx/conf.d/default/server.conf
      - ~/.ssh:/home/app/.ssh
    networks:
      - peakspace-net
    ports:
      - 8000:8000
    dns:
      - 8.8.8.8
      - 1.1.1.1  # DNS alternativo

  db:
    image: mariadb:10.5
    container_name: peakspace-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql/
    networks:
      - peakspace-net


  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-peakspace
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1000M
    ports:
      - 8081:80
    networks:
      - peakspace-net

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: peakspace-mailhog
    logging:
      driver: "none" 
    ports:
      - 1025:1025 
      - 8025:8025 
    networks:
      - peakspace-net

  redis:
    image: redis:alpine
    container_name: peakspace-redis
    ports:
     - "6379:6379"
    networks:
      - peakspace-net
    volumes:
      - redis:/data

  scheduler:
    container_name: peakspace-scheduler
    image: peakspace-api
    depends_on:
      - app
    working_dir: /app
    volumes:
      - ..:/app:cached
      # - vendor:/app/vendor
    networks:
      - peakspace-net
    environment:
      APP_ENV: local
      CONTAINER_ROLE: scheduler
    entrypoint: /usr/local/bin/start.sh

  queue:
    container_name: peakspace-queue
    image: peakspace-api
    working_dir: /app
    depends_on:
      - app
    volumes:
      - ..:/app:cached
      # - vendor:/app/vendor
    networks:
      - peakspace-net
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue
    entrypoint: /usr/local/bin/start.sh

networks:
  peakspace-net:
    name: peakspace-net
    driver: bridge

volumes:
  # vendor:
  #   name: peakspace-api_vendor
  # node_modules:
  #   name: peakspace-api_node_modules
  db:
    name: peakspace-db
  redis:
    name: peakspace-api-redis
